### ISSUE TITLE
MPI examples should not be installed

### ISSUE THREAD

**Issue by matzeri** [opencollab/arpack-ng#10]
in PARPACK/EXAMPLES/MPI/Makefile.am

-bin_PROGRAMS = pzndrv1 psndrv3 pdndrv1 pdndrv3 pssdrv1 pdsdrv1 pcndrv1
+check_PROGRAMS = pzndrv1 psndrv3 pdndrv1 pdndrv3 pssdrv1 pdsdrv1 pcndrv1

to avoid the installation of examples in /usr/bin

**Comment by sylvestre** [comment]
This might break the build because it tries to start the binary without mpirun.
CF commit 2d0900d503ac2c09ef18ef5a918b7c42fad5dbcf

**Comment by matzeri** [comment]
I see that was already included in 
https://github.com/opencollab/arpack-ng/pull/5

but missing from
https://github.com/opencollab/arpack-ng/releases/tag/3.2.0

that I just downloaded and tested, and that gave me the problem.

**Comment by sylvestre** [comment]
Indeed, that is planned for 3.3.0

**Comment by turboencabulator** [comment]
This should be fixed now that 3.3.0 is released.

**Comment by matzeri** [comment]
confirmed.
