### ISSUE TITLE
Test failure on i686-linux-gnu with ATLAS 

### ISSUE THREAD

**Issue by geekboby** [opencollab/arpack-ng#11]
I built arpack-ng with ATLAS 3 installed by full LAPACK interface. Then tried to run tests and get a test failure in 'dnsimp'
This is test-suite log:

 =========================================
   arpack-ng 3.1.3: TESTS/test-suite.log
 ==========================================

 # TOTAL: 2
 # PASS:  1
 # SKIP:  0
 # XFAIL: 0
 # FAIL:  1
 # XPASS: 0
 # ERROR: 0

 .. contents:: :depth: 2

FAIL: dnsimp
 ============

 At line 194 of file /media/home/programs/arpack-ng-3.1.4/TESTS/dnsimp.f (unit = 10, file = '')
 Fortran runtime error: File 'testA.mtx' does not exist

**Comment by geekboby** [comment]
Sorry about that large bold type face. I don't know how it came up.

**Comment by rwirth** [comment]
Could be related to #14. Are you building out of source tree?

**Comment by turboencabulator** [comment]
If it is the out-of-source-tree problem, that should have been fixed in 3.3.0.
