### ISSUE TITLE
Release a new version of arpack-ng

### ISSUE THREAD

**Issue by sylvestre** [opencollab/arpack-ng#114]
@dbeurle  @fghoussen @davydden Are you ok?

**Comment by davydden** [comment]
Please give me a day to try tomorrow those fixes with initialization of variables we discussed in another issue

**Comment by fghoussen** [comment]
OK for me !

**Comment by davydden** [comment]
@sylvestre since https://github.com/opencollab/arpack-ng/issues/82 does not seem to have a solution as of now, I am ok if you release the new version.

**Comment by fghoussen** [comment]
Look at my answer for #82

**Comment by sylvestre** [comment]
3.6.0 released!

**Comment by sylvestre** [comment]
thanks to you all for this work!

**Comment by cfbao** [comment]
Any reason why 3.6.0 is now removed? Anything wrong with it?

**Comment by sylvestre** [comment]
Yes, see https://github.com/opencollab/arpack-ng/issues/123

**Comment by cfbao** [comment]
Thanks for the info.
Although in such scenario I'd prefer to have the release message amended, instead of entirely removed.
