### ISSUE TITLE
Centos 6.6 libtool too old

### ISSUE THREAD

**Issue by m-reuter** [opencollab/arpack-ng#12]
Maybe not really an issue, but on Centos 6.6. the libtool version is 
 libtool --version
ltmain.sh (GNU libtool) 2.2.6b

bootstrap announces:
Libtool version 2.4.2 or higher is required

Is there a way to make this work with earlier libtool versions? Centos 6.6. is only 6months old. Maybe there is a workaround, if only a simple static libarpack.a is needed?

(Furthermore, cmake support would be awesome, to support out-of-source builds)

**Comment by turboencabulator** [comment]
The libtool 2.4.2 requirement was added in 9e319b3c1a6d1cbe074cd52bfbce7b4965149bc4.  From what I can gather, this version of libtool contains some fixes to work with Intel MPI.  If you're not using Intel MPI, then I imagine any version of libtool should work.  Try deleting the LT_PREREQ line (and maybe the few lines before it) from configure.ac, then bootstrap.

**Comment by m-reuter** [comment]
Thanks, that could work. Also upgrading (centos 7 comes with libtool 2.4.2). 
I added cmake support in the meantime, which works for me on multiple platforms, including centos 6.6.. I'll close the issue.
