### ISSUE TITLE
arpack installs very generically named header files that conflict with other packages

### ISSUE THREAD

**Issue by mamoll** [opencollab/arpack-ng#126]
arpack installs a header called "debug.h" in ${prefix}/include that collides with several other packages such as doxygen. See https://trac.macports.org/ticket/56718.

The header stat.h also seems sufficiently generic that I can imagine there are other packages with the same header file name.

**Comment by sylvestre** [comment]
Indeed, sorry about that!

**Comment by 10110111** [comment]
Why not simply move all the headers to a dedicated `arpack` directory? Similarly to how for OpenGL headers we have `GL` directory: e.g. `GL/gl.h`. Then it'll be guaranteed to not conflict.

**Comment by sylvestre** [comment]
I used the easy way to fix that. 
If you feel strongly about it, I will accept your PR to fix that.
