### ISSUE TITLE
github repo must contain generated configure script

### ISSUE THREAD

**Issue by mdejong** [opencollab/arpack-ng#13]
When providing an autoconf enabled project, the maintains should actually run the generation scripts and check the results into the git repo. If not, then everyone who wants to build the software will need to make all the autoconf related tools installed just to build your software. That is not how autoconf is should to work. One should be able to download the source, run the ./configure script and be building right away.

**Comment by gaborcsardi** [comment]
IMO, it definitely should not. As a rule of thumb, the repo should not contain generated files, because their changes bloat the history and make the diffs much harder to read.

Look at the prominent open source projects that use autoconf, I bet most of them do not store configure. E.g. here are some:
https://github.com/git/git
https://github.com/tmux/tmux
https://github.com/stedolan/jq

If you want to install from this repo, just install autoconf, automake and libtool, and you'll be probably fine.

**Comment by mdejong** [comment]
You are simply mistaken about this. See the gcc source tree https://gcc.gnu.org/git/?p=gcc.git;a=tree;h=refs/heads/trunk;hb=refs/heads/trunk or the gdb source tree https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=tree;h=refs/heads/master;hb=refs/heads/master or the Tcl source http://core.tcl.tk/tcl/dir?ci=a8834249fb6afb78&name=unix. The maintainer should take care to make sure the source code can be built as-is without having to download more tools (which some users will not be able to do).

**Comment by gaborcsardi** [comment]
> You are simply mistaken about this.

LOL. :) About what? This is a matter of opinion, and not a fact, how can I be mistaken?

You can try reading around here about the general thinking of good practices:
http://programmers.stackexchange.com/questions/192113/do-i-check-generated-code-in-to-source-control-or-not
http://programmers.stackexchange.com/questions/120477/what-part-of-your-project-should-be-in-source-code-control

Of course this does not mean that they are right, maybe they are wrong, and you are right.

(Owners, sorry for the noise, I am done.)

**Comment by sylvestre** [comment]
arpack-ng used to have the configure into the source tree. It was removed during an update of the build system.

Some projects ship with, some other don't. I don't see any issue with the current solution. If you have another argument (other than installing autoconf and other dependencies), I will be happy to hear it.

**Comment by sylvestre** [comment]
No new argument, closing as wontfix
