### ISSUE TITLE
Bad header file names

### ISSUE THREAD

**Issue by susilehtola** [opencollab/arpack-ng#130]
The C bindings install
```
   /usr/include/arpack.h
   /usr/include/arpack.hpp
   /usr/include/debug-arpack.h
   /usr/include/debug_c.h
   /usr/include/debug_c.hpp
   /usr/include/stat.h
   /usr/include/stat_c.h
   /usr/include/stat_c.hpp
```
The first three are fine, but the last 5 aren't okay since the names are way too generic.

These files should either be installed in an arpack specific directory, or prefixed with ```arpack_```.

**Comment by sylvestre** [comment]
Indeed :/
Don't hesitate to propose a PR, I will do a release right after!

I also realized that they are in the base of the source tree, they should be moved in a subdir.

**Comment by susilehtola** [comment]
Also, ```stat.h``` and ```debug-arpack.h``` appear to be in Fortran, so I'm not really sure if they should even exist?

**Comment by fghoussen** [comment]
Yeah, 100% agree ! I thought to do that at the time... But was in a rush to finish icb.

**Comment by fghoussen** [comment]
As far as I remember `stat.h` and `debug.h` are fortran files : they should be included in the install for fortran users. All `*_c.h`, `*.h`, `*.hpp` files are C/C++ : they should be included in the install for C/C++ users (`_c` means it's a C wrapping [using iso_c_binding] for corresponding fortran files)

**Comment by fghoussen** [comment]
Once fixed for both cmake / autotools, I guess you may revert a48e17f

**Comment by sylvestre** [comment]
yeah, correct!
