### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by apjanke** [opencollab/arpack-ng#132]
Hi, arpack-ng folks,

Could you include a LICENSE file to indicate what license this code is under? Is the licensing situation clear?

**Comment by sylvestre** [comment]
This is already available here:
https://github.com/opencollab/arpack-ng/blob/master/COPYING
It is a bsd license and license situation is clear!

**Comment by apjanke** [comment]
I have no idea how I overlooked that; i must be having a bad day.

Thank you!

**Comment by sylvestre** [comment]
No worries! :)
