### ISSUE TITLE
Please consider renaming files so that it wouldn't conflict with the arpack package

### ISSUE THREAD

**Issue by yurivict** [opencollab/arpack-ng#159]
Currently they conflict, only one of them can be installed at the same time.
This causes incompatibility between any packages using ```arpack``` and ```arpack-ng```.

**Comment by sylvestre** [comment]
arpack-ng is a drop-in replacement of arpack.
arpack being dead and with some severe bugs, I don't see the point of maintaining an arpack package.

Most of the distro kept the arpack package and are just using arpack-ng instead. I recommend you do the same.

**Comment by yurivict** [comment]
I see. Thanks for this information.

**Comment by sylvestre** [comment]
Welcome!
