### ISSUE TITLE
ILP64 support is incomplete

### ISSUE THREAD

**Issue by opoplawski** [opencollab/arpack-ng#163]
I'm seeing segmentation faults in tests of the ILP64 build of arpack in the icb_arpack_c/cpp tests.  I believe this is because the arpack C interface for dsaupd_c and the like are still using a 32-bit integer interface.

**Comment by fghoussen** [comment]
You may be right: I've just discovered (!) that C_INT64_T exists (https://gcc.gnu.org/onlinedocs/gcc-4.5.3/gfortran/ISO_005fC_005fBINDING.html).

I have no ILP64 to test. Can you test on ILP64 replacing all C_INT with C_INT64_T ?

If this works on ILP64, then the whole thing (icb*f90) should be #defined to use C_INT or C_INT64_T according to architecture... If so this must be done **after** merging PR #155
