### ISSUE TITLE
Add explicit instructions for changing install prefix

### ISSUE THREAD

**Issue by adazi** [opencollab/arpack-ng#202]
Just a suggestion: I think it would be helpful if the README had an explicit list of the **cmake** options with their defaults. **cmake** is a great tool, but not everyone knows how to use it. Adding the instructions would make it just a little bit easier for new users to install. 

Specifically, it would be great to include the flag for changing the install prefix ` -DCMAKE_INSTALL_PREFIX=/path/` since that is what I had trouble with, haha.

**Comment by fghoussen** [comment]
This is documented in cmake doc.
