### ISSUE TITLE
configure isn't Bourne shell compatible

### ISSUE THREAD

**Issue by yurivict** [opencollab/arpack-ng#252]
```
checking whether mpic++ supports C++11 features by default... yes
./configure: ${EIGEN3_CFLAGS/...}: Bad substitution
```

According to GNU standards, ```configure``` should be in Bourne shell. https://www.gnu.org/software/autoconf/manual/autoconf-2.64/html_node/Portable-Shell.html

**Comment by fghoussen** [comment]
@yurivict : does #253 help ? @turboencabulator : you tagged FIXME, what do you think ?

**Comment by yurivict** [comment]
@fghoussen Yes, this solved the problem.

**Comment by turboencabulator** [comment]
@fghoussen I'm queuing up some changes to get rid of most of these FIXMEs.  Seems good to me for the meantime.
