### ISSUE TITLE
Please make a release that isn't broken under gcc 10

### ISSUE THREAD

**Issue by joelb123** [opencollab/arpack-ng#261]
Hi. The 3.7.0 release is broken under gcc 10 with the arg mismatch error that is fixed in master branch.   This breaks, among other things, scipy compilation under gcc 10.  Please create a new version from master.

**Comment by sylvestre** [comment]
I wasn't aware. is trunk fixed ?

**Comment by epsilon-0** [comment]
yes, commit #ad82dcbc0beeed5616e2d5a28a089d9785f8b8b8 fixes ggc10 by adding proper checks to variables.

**Comment by rgommers** [comment]
The commit that fixed this was included in the `3.8.0` release, so this issue can be closed.

**Comment by sylvestre** [comment]
thanks
