### ISSUE TITLE
make check fails on 32-bit systems at bug_79_double_complex

### ISSUE THREAD

**Issue by badshah400** [opencollab/arpack-ng#269]
## Expected behavior

Successful run of tests.

## Actual behavior

Running make check fails __only__ on i586 with the following: `FAIL: bug_79_double_complex`.

Full log:
```
# cat TESTS/test-suite.log 
===========================================
   ARPACK-NG 3.7.0: TESTS/test-suite.log
===========================================

# TOTAL: 8
# PASS:  7
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: bug_79_double_complex
===========================

STOP 1
FAIL bug_79_double_complex (exit status: 1)

```

## Where/how to reproduce the problem

- arpack-ng: 3.7.0 + PR #239 + PR #245 (to build against GCC 10)
- OS: openSUSE Tumbleweed
- compiler: GCC 10.1.1
- environment:
```
[  111s] --------------------------------------------------
[  111s] Configuration summary for ARPACK-NG 3.7.0
[  111s] --------------------------------------------------
[  111s] Installation prefix : /usr
[  111s] MPI enabled         : no
[  111s] ICB enabled         : no
[  111s] INTERFACE64         : 0
[  111s] F77                 : gfortran
[  111s] FFLAGS              : -fomit-frame-pointer -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -fPIC
[  111s] FC                  : gfortran
[  111s] FCFLAGS             : -fomit-frame-pointer -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -fPIC
[  111s] CC                  : gcc
[  111s] CFLAGS              : -fomit-frame-pointer -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -fPIC
[  111s] CXX                 : g++
[  111s] CXXFLAGS            : -fomit-frame-pointer -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -fPIC
[  111s] CPPFLAGS            :  -Dsgemm=sgemm_ -Dsnaupd=snaupd_ -Dsneupd=sneupd_ -Ddnaupd=dnaupd_ -Ddneupd=dneupd_ -Dcheev=cheev_
[  111s] BLAS                : -lblas
[  111s] LAPACK              : -llapack
[  111s] EIGEN               : 
[  111s] LIBS                : 
[  111s] LDADD               : 
[  111s] --------------------------------------------------
[  111s] Configuration OK
[  111s] --------------------------------------------------
```
- configure: See above

## Steps to reproduce the problem

- Build on i586 with above configuration
- Run make check

## Error message

See full contents of `test-suite.log` above.

## Additional remarks

Full spec file and build logs at
https://build.opensuse.org/package/show/science/arpack-ng?rev=40

**Comment by fghoussen** [comment]
Increase `-fmax-stack-var-size` ?

> [   76s] bug_79_double_complex.f:73:37:
[   76s] 
[   76s]    73 |      &                  v(ldv,maxncv), workd(3*maxn),
[   76s]       |                                     1
[   76s] Warning: Array 'v' at (1) is larger than limit set by '-fmax-stack-var-size=', moved from stack to static storage. This makes the procedure unsafe when called recursively, or concurrently from multiple threads. Consider using '-frecursive', or increase the '-fmax-stack-var-size=' limit, or change the code to use an ALLOCATABLE array. [-Wsurprising]

@caliarim : changing test check according to a tolerance ? (`res1` and `res2` are `double precision`)

```
>> git diff
diff --git a/TESTS/bug_79_double_complex.f b/TESTS/bug_79_double_complex.f
index 49b5ae2..42afa79 100644
--- a/TESTS/bug_79_double_complex.f
+++ b/TESTS/bug_79_double_complex.f
@@ -217,7 +217,7 @@ c           %----------------------------------%
             go to 9000
          end if
  9000 continue
-      if (res1 .ne. res2) then
+      if (abs(res1 - res2) < 1.E-10) then
          stop 1
       end if
       end

```

**Comment by badshah400** [comment]
That does it, thanks!

```diff
--- arpack-ng-3.7.0.orig/TESTS/bug_79_double_complex.f
+++ arpack-ng-3.7.0/TESTS/bug_79_double_complex.f
@@ -217,7 +217,7 @@ c           %---------------------------
             go to 9000
          end if
  9000 continue
-      if (res1 .ne. res2) then
+      if (abs(res1 - res2) > 1.E-10) then
          stop 1
       end if
       end
```

**Comment by fghoussen** [comment]
@badshah400 : the test must be `<` to make sense !... If @caliarim approve this (may not be the right check)

```
-      if (res1 .ne. res2) then
+      if (abs(res1 - res2) < 1.E-10) then
```

**Comment by caliarim** [comment]
res1 and res2 should be the result of the same operation, i.e. the multiplication of a given vector by a given matrix. They should be exactly the same vectors, even in machine arithmetic. If you can prove that the problem is the value of -fmax-stack-var-size, then it can be safe to relax the tolerance. Anyway, I think 1e-10 is too large.

**Comment by badshah400** [comment]
> @badshah400 : the test must be `<` to make sense !... If @caliarim approve this (may not be the right check)
> 
> ```
> -      if (res1 .ne. res2) then
> +      if (abs(res1 - res2) < 1.E-10) then
> ```

OK, I am probably confused. I understand that when the condition `res1 .ne. res2` is met, the program ends with an error: `STOP 1`, since `res1` must be equal to `res2` for the test to be correct. The equivalent of this `.ne.` in terms of thresholds would be `abs(res1 - res2) > THRESHOLD`, wouldn't it? In other words `abs(res1-res2) < THRESHOLD` would be the condition for the program to stop without error.

@caliarim I agree. I shall check with changes to the value of `-fmax-stack-var-size`, but in the meanwhile this works too (why using `.ne.` doesn't work beats me — I am not a fortran person):
```
-      if (res1 .ne. res2) then
+      if (abs(res1 - res2) > 0.0D0) then
```

**Comment by fghoussen** [comment]
@caliarim : using lowest double release-or-debug precision ? or highest (1.e-15) ?

```
-      if (res1 .ne. res2) then
+      if (abs(res1 - res2) < 1.E-17) then
```

**Comment by caliarim** [comment]
ah ah we are all confused! I try again: res1 and res2 should be equal, because results of the same operation. I understand that they can be slightly different due to a different number of bits used when passing variables to subroutines. So, the test should fail if they are too much different. Therefore, something like
```
if (abs(res1 - res2) > 1.e-15 stop
```
@badshah400 can you put
```
write(6,*) res1 - res2
```
in the file, before the if statement, and report us what you see?

**Comment by badshah400** [comment]
> can you put
> 
> ```
> write(6,*) res1 - res2
> ```
> 
> in the file, before the if statement, and report us what you see?

It gives 0 all right, specifically `0.0000000000000000` .

**Comment by caliarim** [comment]
So, res1 .ne. res2 AND resi1 - res2 is 0 in your case? This is new math...

**Comment by badshah400** [comment]
I suspect I need to print the result in EXP notation to really see how small it is.

**Comment by caliarim** [comment]
```
write(6,'(1x,e24.16)') res1-res2
```

**Comment by badshah400** [comment]
It is zero, `0.0000000000000000E+00` that's why my check for `if (abs(res1 - res2) > 0.0D0) then stop` works (even on i586). I don't understand why `res1 .ne. res2` doesn't work either, but like I said in my description it is a weird problem that `.ne.` does work on x86_64 but fails on i586.

**Comment by caliarim** [comment]
maybe .ne. performs a bit by bit comparison, while abs(res1 - res2) works on the double precision part. If abs(res1 - res2) > 0.0d0 works for you (that is, the test passes), I suggest to change to it.

**Comment by badshah400** [comment]
OK, I confirm that `if (abs(res1 - res2) > 0.0D+0) then stop` works. Should I submit a PR or do you think this isn't all that useful upstream? Many thanks for the help in figuring this out, both of you!

**Comment by fghoussen** [comment]
@badshah400 : feel free to PR ! Adding some stuff like `write(6,'(a,3e24.16)') "ERROR res: ", res1, res2, res1-res2` on error before `stop` maybe be useful.
