### ISSUE TITLE
arpack fails configuration on ubuntu 20.4 -- conflict with patch for GCC-10 on macOS

### ISSUE THREAD

**Issue by lteneyck** [opencollab/arpack-ng#273]
## Expected behavior

"brew install arpack" should compile and install 

## Actual behavior

configure: error: cannot compile a simple Fortran program
See `config.log' for more details.

## Where/how to reproduce the problem

- arpack-ng: release 3.7.0_5 SHA "972e3fc3cd0b9d6b5a737c9bf6fd07515c0d6549319d4ffb06970e64fa3cc2d6"

- OS: ubuntu 20.4
- compiler: gcc (Homebrew GCC 5.5.0_7) 5.5.0, intel
- environment: export FFLAGS=-fallow-argument-mismatch

## Steps to reproduce the problem
Probably fails on systems NOT***  using LLVM 10 and clang

**The GIST is HERE**:  https://gist.github.com/655a5091d2d41ff135ac6c95c3daab98

I edited the formula arpack.rb to comment out the setting of FFLAGS and it compiled.
Here is the diff -c

/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/arpack.rb	2020-07-09 11:21:45.701093807 -0700
--- arpack-new.rb	2020-07-09 11:54:12.781915955 -0700
***************
*** 36,42 ****
  
      # Fix for GCC 10, remove with next version
      # https://github.com/opencollab/arpack-ng/commit/ad82dcbc
!     args << "FFLAGS=-fallow-argument-mismatch"
  
      system "./bootstrap"
      system "./configure", *args
--- 36,42 ----
  
      # Fix for GCC 10, remove with next version
      # https://github.com/opencollab/arpack-ng/commit/ad82dcbc
!     # args << "FFLAGS=-fallow-argument-mismatch"
  
      system "./bootstrap"
      system "./configure", *args

At some level a check has to be made to see which system is compiling the code,
but for now that is beyond my expertise.

**Comment by lteneyck** [comment]
Issue was fixed in linuxbrew, which is where I should have reported it in the first place.

**Comment by sylvestre** [comment]
Is there a patch we should apply here?
Thanks

**Comment by lteneyck** [comment]
No, there was a parameter passed to configure that was needed for macOS but
caused a failure on linux. The formula has been fixed to check which OS is
the target. There is no problem with arpack itself.
