### ISSUE TITLE
Attach a post-bootstrap tarball to github releases for 3.3.0

### ISSUE THREAD

**Issue by tkelman** [opencollab/arpack-ng#29]
(and future releases) for installation on systems without autotools present. Thanks!

**Comment by zerothi** [comment]
I agree, I can't even do boostrap with the 3.3.0, it says "missing ltmain.sh".
Creating the configure would help enormously :)

**Comment by sylvestre** [comment]
I think this is a bug of the issue #13

**Comment by zerothi** [comment]
I think the argument made in #13 is correct, the configure script shouldn't be in the tree, however, one can create new draft releases where a _proper_ configure is present, without having anything to do with the commit tree. I think this is recommendable.

I.e. the release process should be:
```
git tag -a ...
git push --tags
wget https://github.com/opencollab/arpack-ng/archive/<version>.tar.gz
tar xfz <version>.tar.gz
cd arpack-ng-<version>
./boostrap
cd ../
tar cfz arpack-ng-<version>.tar.gz arpack-ng-<version>
<create draft release>
```
There are a multitude of users who do not have the build utils, and besides using the correct version of auto(re)conf is a hazzle on various platforms due to different distribution versions.

**Comment by tkelman** [comment]
Right. This is a separate issue, I'm fine with the development master not containing generated autotools files, I'm just asking about release tarballs. Please make your recent releases as easy to install fron the tarball as the old ones, or a fair number of users will stay pinned to the last easy-to-build version to avoid imposing any more build-time dependencies. Should be just a minute or two of work per release.

**Comment by zerothi** [comment]
@sylvestre do you still consider the above suggestion as wont-fix?

**Comment by sylvestre** [comment]
I don't like manual steps. So, I won't do what you are proposing. 
However, if you make a PR to include back the configure, Makefile.in, etc, I will approve it.

**Comment by tkelman** [comment]
That would mean more manual steps of having to regen, git add, and commit the files any time you make changes to the .ac or .am files, which would likely end up being more manual steps than once per release in the long run.

You're using Travis, so it should be possible to write a script that responds to a release event webhook and automatically uploads and attaches the generated tarball to github releases, but you'd need to set up an encrypted variable with the credentials for it. There is no webhook that I can see for "tag created" events, only "release," so you would have to manually go to https://github.com/opencollab/arpack-ng/releases/new, select a tag, and click publish after pushing each release tag. That part might also be automatable from travis via the github API with the right permissions set up.

**Comment by sylvestre** [comment]
> That would mean more manual steps of having to regen, git add, and commit the files any time you make changes to the .ac or .am files, which would likely end up being more manual steps than once per release in the long run.
Adding new files happen rarely. arpack-ng is a project on maintenance mode. I don't see that as an issue.

**Comment by turboencabulator** [comment]
I have a warning if anyone does decide to re-add all the generated files to the repo.  If you want to develop but don't have the same version of autoconf/automake as what was used to generate the files, then it really turns into a mess when you change anything.  All those generated files get regenerated for your local version.  You probably don't want to commit them because it could create merge conflicts, but then again you do want to commit them so the generated files won't be stale.

If you're not able to host a `make dist` tarball anywhere, then maybe cmake solves this.

**Comment by ViralBShah** [comment]
Can we have checked in autoconf/automake generated files for now, and move to cmake when it is fully ready? We'd really like to use the fixes in arpack-ng 3.3 with Julia, and this is the only issue that needs resolving.

**Comment by zerothi** [comment]
Please do not move fully to cmake.
It is a pain to customise with fine granularity!

--

Kind regards Nick Papior

**Comment by tkelman** [comment]
We just need a single shared library so it's easier for us to just not use configure at all.

**Comment by markcmiller86** [comment]
So, I see my original ticket and this one has been closed and I checked 3.3.0 and 3.4.0 tarballs for a configure. There is configure.ac but no configure. To then configure arpack-ng from sources using configure.ac, I need to download and install the monster that is autotools even if I am a version behind 2.67 (that required by arpack-ng). I see there was some discussion of preparing release tarballs with additional files not included in the repo. That sounds like a great idea!

But, alas, it sounds like there are other technical difficulties in making that happen. So, those technical difficulties appear to have trumped user-friendliness. IMHO, if you are *serious* about reducing barriers to entry/use (and not simply adhering to parochial policies about what is good or bad practice as far as files you include in your repo), you would address this issue even if it means including configure in your repo. Plenty of projects do this and are able to avoid many of the problems you seem to be concerned with; history bloat or auto-tools version thrashing.

**Comment by turboencabulator** [comment]
Does it work if you change AC_PREREQ to 2.67?  There are programs that come with autotools (autoscan, autoupdate) that help generate configure.ac, and AFAIK they fill in AC_PREREQ with the latest even when it might not be required.  I don't know of a good way to figure out the minimum version required.

**Comment by markcmiller86** [comment]
Yes, it does. That trick so far works. Will it continue to do so? Will it work on other platforms that have even older versions of autotools installed? Maybe. Maybe not. My main point, however, is that I shouldn't have to worry about having autotools available to configure a package. That is the *whole* point of a configure script that is vanilla sh code. It *works* everywhere so you don't need anything else.

**Comment by turboencabulator** [comment]
If you intend on building from source, you're going to need the tools to do it.  There is also cmake which serves the same purpose and requires you to have that installed, and I don't see anyone complaining about that.

**Comment by nalimilan** [comment]
> If you intend on building from source, you're going to need the tools to do it.

Autotools have never been intended to be required by users which merely build tarballs, only by maintainers. They are complex and version-sensitive; only resulting scripts are made to be portable.

Also, the fact that there's a CMake support is great, but it's totally orthogonal to the question of how the autotools build should work.

**Comment by markcmiller86** [comment]
I think the argument @turboencabulator is making is that if a cmake configuration requires CMake, then why should having the autoconf configuration *require* autotools be any more of a problem?

Short answer: CMake has been around for 15+ years and *is* arguably better than Autoconf in many respects. However, the very fact that it *does*require* you to have CMake before you can configure anything that uses it is the reason that for the last 15 years it hasn't succesfully obsoleted autoconf. Autoconf was *designed* to only require the shell to configure. IMHO, any project using it differently is missing the whole point. And, then I agree, why not just use CMake?
