### ISSUE TITLE
Issues with source code snaitr.f

### ISSUE THREAD

**Issue by keyi-ray-liu** [opencollab/arpack-ng#293]
## Expected behavior

Compile

## Actual behavior

Would not get past make. A lot of errors in snaitr.f

## Where/how to reproduce the problem

- arpack-ng release
- OS: redhat linux
- compiler: gcc 
- configure: ./configure 

Configuration summary for ARPACK-NG 3.9.0

Installation prefix : /usr/local
MPI enabled         : no
ICB enabled         : no
INTERFACE64         : 0
F77                 : g77
FFLAGS              : -g -O2
FC                  : gfortran
FCFLAGS             : -g -O2
CC                  : gcc
CFLAGS              : -g -O2
CXX                 : g++
CXXFLAGS            : -g -O2
CPPFLAGS            :  -Dsgemm=sgemm_ -Dsnaupd=snaupd_ -Dsneupd=sneupd_ -Ddnaupd=dnaupd_ -Ddneupd=dneupd_ -Dcheev=cheev_
MPI_Fortran_LIBS    :
MPI_C_LIBS          :
MPI_CXX_LIBS        :
BLAS                : -lblas
LAPACK              : -llapack
EIGEN               :
LIBS                :
LDADD               :

## Steps to reproduce the problem

I was following the steps in README

sh bootstrap
./configure 
make (failed)
-
-
-

## Error message

/bin/sh ../libtool --tag=F77   --mode=compile g77  -g -O2 -c -o snaitr.lo snaitr.f
libtool: compile:  g77 -g -O2 -c snaitr.f  -fPIC -o .libs/snaitr.o
snaitr.f: In subroutine `snaitr':
snaitr.f:374:
               call ivout (logfil, 1, [j], ndigit,
                                      ^
Unrecognized character at (^) [info -f g77 M LEX]
snaitr.f:374:
               call ivout (logfil, 1, [j], ndigit,
                    1                             2
Invalid token at (2) in expression or subexpression at (1)
snaitr.f:376:
               call svout (logfil, 1, [rnorm], ndigit,
                                      ^
Unrecognized character at (^) [info -f g77 M LEX]
snaitr.f:376:
               call svout (logfil, 1, [rnorm], ndigit,
                    1                                 2
Invalid token at (2) in expression or subexpression at (1)
snaitr.f:396:
                  call ivout (logfil, 1, [j], ndigit,
                                         ^
Unrecognized character at (^) [info -f g77 M LEX]
snaitr.f:396:
                  call ivout (logfil, 1, [j], ndigit,
                       1                             2
Invalid token at (2) in expression or subexpression at (1)
snaitr.f:376: warning:
               call svout (logfil, 1, [rnorm], ndigit,
                    1
snaitr.f:658: (continued):
               call svout (logfil, 2, xtemp, ndigit,
                    2
Too many arguments for `svout' at (2) versus invocation at (1) [info -f g77 M GLOBALS]
snaitr.f:376: warning:
               call svout (logfil, 1, [rnorm], ndigit,
                    1
snaitr.f:660: (continued):
               call svout (logfil, j, h(1,j), ndigit,
                    2
Too many arguments for `svout' at (2) versus invocation at (1) [info -f g77 M GLOBALS]
snaitr.f:724:
               call ivout (logfil, 1, [j], ndigit,
                                      ^
Unrecognized character at (^) [info -f g77 M LEX]
snaitr.f:724:
               call ivout (logfil, 1, [j], ndigit,
                    1                             2
Invalid token at (2) in expression or subexpression at (1)
snaitr.f:376: warning:
               call svout (logfil, 1, [rnorm], ndigit,
                    1
snaitr.f:729: (continued):
                   call svout (logfil, 2, xtemp, ndigit,
                        2
Too many arguments for `svout' at (2) versus invocation at (1) [info -f g77 M GLOBALS]
make[1]: *** [snaitr.lo] Error 1

**Comment by fghoussen** [comment]
Weird. `^ Unrecognized character` what's your locale ?

**Comment by keyi-ray-liu** [comment]
Everything is en_US.UTF-8

**Comment by fghoussen** [comment]
Weird. Compiler version ? Try to upgrade them ?

**Comment by fghoussen** [comment]
@keyi-ray-liu : did you try ` -ffree-form` and/or `-cpp` ?

**Comment by keyi-ray-liu** [comment]
Hello. Actually I tried on another cluster and the compilation went through. It's very likely due to the compiler version so I will get back to you after everything is updated by the admin. Thanks

**Comment by sylvestre** [comment]
ok, thanks!
