### ISSUE TITLE
All docker runs fail

### ISSUE THREAD

**Issue by fghoussen** [opencollab/arpack-ng#309]
## Expected behavior

Docker runs should be OK.

## Actual behavior

Docker runs fail with this kind of errors
> +sudo docker pull centos:latest
Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

## Notes, remarks

Not sure what the process should be, but, my understanding from https://github.com/marketplace/actions/docker-login (github container registry GCR) is that :

1. @sylvestre , you must (looks like I can't) enable GCR for the opencollab organization (https://docs.github.com/en/packages/working-with-a-github-packages-registry/enabling-improved-container-support-with-the-container-registry - Enabling the Container registry for your organization account)
2. push this
```
>> git diff
diff --git a/.travis.yml b/.travis.yml
index 9cdfda8..5084edd 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -44,6 +44,14 @@ stages:
   - name: debian_interface64
 
 jobs:
+  login:
+    steps:
+      - name: Login to GitHub Container Registry
+      - uses: docker/login-action@v1.9.0
+        with:
+          registry: ghcr.io
+          username: ${{ github.opencollab }}
+          password: ${{ secrets.GITHUB_TOKEN }}
   include:
   # opensuse: "recent" systems with ICB
   #   note: when you PR, docker-cp provides, in the container, the branch associated with the PR (not master where there's nothing new)
```

... And hope this is enough to get docker back ?!...

**Comment by fghoussen** [comment]
@sylvestre  : did you had time to have a look at this ?

**Comment by sylvestre** [comment]
@fghoussen i missed your message, sorry
I will have a look asap

**Comment by fghoussen** [comment]
@sylvestre : as far as I understand (not sure), you may try, as github/opencollab **admin** (I'm not), this 3-steps process

1.  Create a docker account here https://hub.docker.com/signup and a personal access token (PAT) for docker https://docs.docker.com/docker-hub/access-tokens

2. Create a secret for github/opencollab (you need to be **admin** for that) where you store your docker login and PAT : https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-an-organization

3. Try to push something like this on a test branch... And check out if this works or not

```
>> git diff
diff --git a/.travis.yml b/.travis.yml
index 9cdfda8..5084edd 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -44,6 +44,14 @@ stages:
   - name: debian_interface64
 
 jobs:
+  login:
+    steps:
+      - name: Login to GitHub Container Registry
+      - uses: docker/login-action@v1.9.0
+        with:
+          registry: ghcr.io
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_TOKEN }}
   include:
   # opensuse: "recent" systems with ICB
   #   note: when you PR, docker-cp provides, in the container, the branch associated with the PR (not master where there's nothing new)
```

**Comment by sylvestre** [comment]
@fghoussen I gave you admin permissions, it will be easier this way :)
Just don't break everything ;)

**Comment by fghoussen** [comment]
@sylvestre : I'll try to test that soon when possible :)

**Comment by fghoussen** [comment]
@sylvestre : did you get mails from TravisCI ?

**Comment by sylvestre** [comment]
Yes
time to move to github actions?

**Comment by fghoussen** [comment]
No I guess travis is back !... Now let's see if docker is too :)

**Comment by sylvestre** [comment]
yeah, I just tried to do it (or maybe you did)

**Comment by fghoussen** [comment]
Not sure github actions enables to run on osx and on old ubuntu (precise, ...)

**Comment by fghoussen** [comment]
github action offers only latest dist (ubuntu, osx and even windows) but not old ones : https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on. Coverage should be possible as it's external service but still need to be tested. No idea about eventual pricing. @sylvestre : what do you think ?

**Comment by sylvestre** [comment]
gh action would be free
coverage works well for free

And for the old system, too bad?

**Comment by fghoussen** [comment]
Not sure which move is the best ?!... Old sys may be run through docker ? Or dropped ?
First, let's check out if github actions could work and how ?
Would be easier to stick to travis : can you ask them what has changed (plan) for public open-source repo like arpack-ng ?

**Comment by fghoussen** [comment]
gh runs at my side since where are not merged in master I guess : https://github.com/fghoussen/arpack-ng/actions

**Comment by fghoussen** [comment]
Moved to github actions
