### ISSUE TITLE
Non constant array size in icb_arpack_c.c

### ISSUE THREAD

**Issue by dariomangoni** [opencollab/arpack-ng#312]
## Actual behavior

All the constant-size stack arrays defined in `icb_arpack_c.c` have a size defined by an `a_int` variable that does not have the required constness.
e.g.
```
a_int N = 1000;
double resid[N];
```
thus giving the error:
`Expression must have a constant value`

It would probably be better to use `malloc` or either use `#define`.

## Where/how to reproduce the problem

- arpack-ng: 0a655d918d558ef97881db2760668b8d1e3b4bc1
- OS: Win10
- compiler: MSVC

## Steps to reproduce the problem

- run icb_arpack_c.c

**Comment by wztzjhn** [comment]
@fghoussen this seems to be fixed by my recent clean.

**Comment by fghoussen** [comment]
Fixed by #371
