### ISSUE TITLE
replace non-standard functions such as dimag with (newish) standard ones

### ISSUE THREAD

**Issue by dimpase** [opencollab/arpack-ng#316]
## Expected behavior

Code compiles with NAGs `nagfor` compiler

## Actual behavior

It does not, one needs to follow the advice given on https://www.nag.com/content/nag-fortran-compiler-frequently-asked-questions#faq25 - e.g. `dimag()` should be replaced with `aimag()`, etc.

## Where/how to reproduce the problem

- arpack-ng: current master
- OS: mac; linux
- compiler: nagfor 7.0
- environment: Homebrew
- configure: ./configure FC=nagfor
- input data: n/a

## Steps to reproduce the problem
```
./bootstrap
./configure FC=nagfor
make
```

## Notes, remarks

the fix is here: https://github.com/dimpase/arpack-ng/commit/edd491103495bf4c8121c1d94003ba20c1db1dc1

 I'm just not sure whether a PR like this will be considered.

**Comment by fghoussen** [comment]
CI down at the time: this will wait until it's back up. Is `nagfor` available on ubuntu?

**Comment by dimpase** [comment]
I can fix you up a basic CI on GitHub, if you like. (I tested this patch with gfortran 11 on Fedora, too, it works just fine).

`nagfor` normally cost money, so no, it's not on any free service I am aware of.

**Comment by fghoussen** [comment]
We look for a complete-full CI solution : https://github.com/opencollab/arpack-ng/pull/315. You can help here if you like.
CI will be first. We can only accept your modifications if CI stays green.

**Comment by dimpase** [comment]
all tests pass on #318

**Comment by fghoussen** [comment]
Fix merged.
