### ISSUE TITLE
Tautological compare in MATRIX_MARKET/arpackSolver.hpp

### ISSUE THREAD

**Issue by StefanBruens** [opencollab/arpack-ng#319]
https://github.com/opencollab/arpack-ng/blob/5c28eac0b38babd187fdccb3005817ce4d5a4fe2/EXAMPLES/MATRIX_MARKET/arpackSolver.hpp#L662

`nbCV` is compared with itself, which is obviously wrong.

One of the two `nbCV`s is probably meant to be the arpackSolver member variable, while the other one is the value read from the stream.

**Comment by fghoussen** [comment]
@StefanBruens : you're right, thanks for reporting!
If I remember well should be `if (nbCV < nbDim) nbCV = nbDim;` in case you restart with a smaller `nbDim` that the one used in the previous run. I'll have a look and fix another (old-not-fixed) bug soon.

**Comment by fghoussen** [comment]
Closing: should be fixed
