### ISSUE TITLE
Use `-ff2c` in the default build on macOS + Accelerate

### ISSUE THREAD

**Issue by ViralBShah** [opencollab/arpack-ng#326]
## Expected behavior

Tests should not segfault

## Actual behavior

The following tests FAILED:
	  3 - cnbdr3_ex (SEGFAULT)
	 29 - znbdr1_ex (SEGFAULT)
	 35 - cndrv3_ex (SEGFAULT)
	 37 - zndrv1_ex (SEGFAULT)
	 38 - zndrv2_ex (SEGFAULT)
	 58 - znsimp_ex (SEGFAULT)

## Where/how to reproduce the problem

- arpack-ng: commit 645db9e6472283408563e3e2dc99c5deb8272c5d
- OS: macOS 12.0.1
- compiler: Apple clang version 13.0.0 (clang-1300.0.29.3), gcc version 11.2.0 (Homebrew GCC 11.2.0_1) 
- environment: on macOS, it is using Accelerate
- configure: cmake -D EXAMPLES=ON -D MPI=OFF -D BUILD_SHARED_LIBS=ON ..
- input data: default tests

## Steps to reproduce the problem

make test

**Comment by fghoussen** [comment]
@ViralBShah : not surprised, feel free to propose a PR! When CI was TravisCI (moved to github actions recently), on macos (don't remember the release), we had to limit tests to only a subset as the others were crashing (c/z tests as far as I remember). Now with github actions macos box, problems disappeared. Did you try to use accelerate and ff2c ? https://github.com/opencollab/arpack-ng/blob/645db9e6472283408563e3e2dc99c5deb8272c5d/.github/workflows/jobs.yml#L169

**Comment by ViralBShah** [comment]
I just did the default `cmake` thing which did use Accelerate. I assume that will use ff2c as well.

**Comment by fghoussen** [comment]
Not so sure for `-ff2c` : you may be right, but, check it out!

**Comment by ViralBShah** [comment]
Since the `cmake` build automatically detects the pressence of Accelerate, can't it automatically use `-ff2c` as well?

**Comment by ViralBShah** [comment]
Using this build fixes macOS for me.
```
LIBS="-framework Accelerate" FFLAGS="-ff2c -fno-second-underscore" FCFLAGS=
"-ff2c -fno-second-underscore" cmake -D EXAMPLES=ON -D MPI=OFF -D BUILD_SHARED_LIBS=ON ..  
```

**Comment by fghoussen** [comment]
Closing issue as problem is fixed.
