### ISSUE TITLE
arpack with INTERFACE64=1 LIBSUFFIX=_64 and mingw64

### ISSUE THREAD

**Issue by 3rav** [opencollab/arpack-ng#327]
I try to do msys2/mingw package with contains two version of arpack: normal and int64. haw I can change include dir to: 
.../include/arpack64?

I use configure file.

**Comment by fghoussen** [comment]
You need to modify *.pc.in and *.cmake files.

**Comment by 3rav** [comment]
https://github.com/opencollab/arpack-ng/pull/330

**Comment by fghoussen** [comment]
Should be fixed by #356. If not, do not hesitate to reopen.
