### ISSUE TITLE
icb_parpack_cpp.cpp fail test when changing number eigenvalues

### ISSUE THREAD

**Issue by WeiHou1996** [opencollab/arpack-ng#332]
Hi, I compiled the code using Intel oneAPI with MKL. I compiled icb_parpack_cpp.cpp and ran it. It seems that when I run the code to compute complex eigenvalues, it works alright when nev = 1. However, when nev is set to more than 1, the code fails when running in parallel. Somehow, when the number of processes, n, is smaller than 7, the code gives n largest identical eigenvalues of 1000+1000i. 

I compiled the code using the following cmake command:
cmake -D EXAMPLES=ON -D MPI=ON -D BUILD_SHARED_LIBS=ON -D ICB=ON -DCMAKE_CXX_COMPILER=icpc -DCMAKE_C_COMPILER=icc -DCMAKE_FC_COMPILER=ifort ..
with BLAS set to Intel10_64lp

Is there something I'm doing wrong or it is something I need to change in the code?

Thank you for your help!

**Comment by fghoussen** [comment]
You may try `BLA_VENDOR=Intel10_64lp cmake -D EXAMPLES=ON -D MPI=ON -D BUILD_SHARED_LIBS=ON -D ICB=ON -DCMAKE_CXX_COMPILER=icpc -DCMAKE_C_COMPILER=icc -DCMAKE_FC_COMPILER=ifort ..` or specify FLAGS by hand using intel link advisor https://www.intel.com/content/www/us/en/developer/tools/oneapi/onemkl-link-line-advisor.html#gs.n6ssms

**Comment by WeiHou1996** [comment]
Thanks for the reply! Let me try it and see if that works!

**Comment by WeiHou1996** [comment]
I added the following:
add_compile_options(-DMKL_ILP64  -I"${MKLROOT}/include")
and changed the target_link_library for icb_parpack_cpp to the following
target_link_libraries(icb_parpack_cpp parpack arpack BLAS::BLAS LAPACK::LAPACK ${EXTRA_LDFLAGS} MPI::MPI_CXX -Wl,--start-group ${MKLROOT}/lib/intel64/libmkl_intel_ilp64.a ${MKLROOT}/lib/intel64/libmkl_sequential.a ${MKLROOT}/lib/intel64/libmkl_core.a -Wl,--end-group pthread m dl)

After these modifications, the program compiles but just hangs when running. Do you have any idea why is that?

**Comment by fghoussen** [comment]
Very unlikely I could help you from here! Follow some working example like https://github.com/opencollab/arpack-ng/blob/645db9e6472283408563e3e2dc99c5deb8272c5d/.github/workflows/jobs.yml#L82, or do things by hand following intel link advisor. Personal experience: hanging means type mismatch (link passed - but shouldn't - so runtime freezes).

**Comment by fghoussen** [comment]
Fixed by f36eb6c75dc686c8cebdaca0106422d77b04152d
