### ISSUE TITLE
add topics/tags in the About section to aid search

### ISSUE THREAD

**Issue by Beliavsky** [opencollab/arpack-ng#340]
I suggest adding the topics `eigenvalue`, `linear-algebra`, `arpack` in the About section.

I raised this before, and it was closed, but the About section should have tags as seen in the About section of https://github.com/jchristopherson/linalg . How to add topics is described at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics .

The point of adding topics is that a search such as `topic:eigenvalue` will bring up the repo.

**Comment by fghoussen** [comment]
Done. You could reopen the previous issue.
