### ISSUE TITLE
Problems linking to OpenBLAS

### ISSUE THREAD

**Issue by dansavio** [opencollab/arpack-ng#36]
I've tried both the automake and the CMake methods - same problem.  I can build arpack-ng (while linking it to libopenblas.a) successfully, but when i go to use the library i always get:

libarpack.a(cgetv0.o): In function `cgetv0_':
arpack-ng/SRC/cgetv0.f:233: undefined reference to `clarnv_'
libarpack.a(dgetv0.o): In function `dgetv0_':
arpack-ng/SRC/dgetv0.f:236: undefined reference to `dlarnv_'
libarpack.a(sgetv0.o): In function `sgetv0_':
arpack-ng/SRC/sgetv0.f:236: undefined reference to `slarnv_'
libarpack.a(zgetv0.o): In function `zgetv0_':
arpack-ng/SRC/zgetv0.f:233: undefined reference to `zlarnv_'

Using nm (and strings), i verify that my libopenblas.a does indeed define these symbols.  So what is the problem?

**Comment by dansavio** [comment]
To add some clarity:
Using "nm", i am seeing that libopenblas.a does define, for example, clarnv_:

nm libopenblas.a | grep clarnv_
outputs:
0000000000000000 T clarnv_

If i do the same to the produced libarpack.a, here's what I see:
                 U clarnv_

In the CMakeLists.txt for arpack-ng, i am explicitly setting the arpack target to link to my static OpenBLAS library:
target_link_libraries(arpack ${OPENBLAS_LIBRARIES})

I have triple-checked that ${OPENBLAS_LIBRARIES} is pointing to the correct location for libopenblas.a, and it is.

**Comment by thrasibule** [comment]
Does it work if you build a shared library instead?

**Comment by dansavio** [comment]
The problem was the linking order - i needed to link libopenblas.a after arpack.
