### ISSUE TITLE
[Documentation] Please provide a separate "INSTALLATION" (or perhaps compilation) subsection in the main README

### ISSUE THREAD

**Issue by rubyFeedback** [opencollab/arpack-ng#374]
Right now I have to scan the whole page; my primary question, though, was whether I could compile it from source on my linux box. I'll soon try out anyway, but having a clear subsection with a header would be nice. Right now there is no header, so please can someone re-structure the main README a little?

Please provide a separate "INSTALLATION" (or perhaps compilation) subsection in the main README. Right now I have to scan the whole page; my primary question, though, was whether I could compile it from source on my linux box. I'll soon try out anyway, but having a clear subsection with a header would be nice. Right now there is no header, so please can someone re-structure the main README a little?

I often have multiple tabs open in my browser, so I don't pay as much attention. My next step will be to simply git clone the homepage here and then see if I can compile it. Hopefully it will work ...

**Comment by sylvestre** [comment]
I think it is clear enough.
a search on the page with "build" give immediately the two methods
