### ISSUE TITLE
Better README and ARPACK Website 

### ISSUE THREAD

**Issue by vickysharma0812** [opencollab/arpack-ng#382]
## Expected behavior

Please see the modified README file here:

- [ARPACK-NG](https://github.com/vickysharma0812/arpack-ng)

## Notes, remarks

- Next, I want to provide more details on installation using CMake (I am not much familiar with ` ./configure` and auto-tools)
- I want to provide documentation through Github-pages and `Mkdocs`. 

Best wishes
Vikas Sharma

**Comment by fghoussen** [comment]
Sounds good! :)

**Comment by fghoussen** [comment]
Merged, closing.
