### ISSUE TITLE
Name collision and include directory (`debug.h`and co)

### ISSUE THREAD

**Issue by FabienPean** [opencollab/arpack-ng#395]
> > Agree. Better to write #include <arpack/arpack.hpp> rather than #include <arpack.hpp>. However, changing this might break some capability as people used to write #include <arpack.hpp> in their codes.
>
> Agree too. IMO, can't afford backward compatibility (no pay here...) : people will have to move on and that's no big deal

_Originally posted by @fghoussen in https://github.com/opencollab/arpack-ng/issues/296#issuecomment-798004181_

I remarked this potential problem too, if the opinion is still the same, should it be solved before marking the new version #394 ?

IMO, calling `#include<arpack.hpp>` is not such a big, the potential collision issues come from the other headers (debug, stat). (Is there actually people relying on them ?). On the CMake side, I can think of several options, more or less breaking.

**Comment by fghoussen** [comment]
Would say we are already using `#include<arpack.hpp>`.

ILP64 may modify `arpackdef.h` https://github.com/opencollab/arpack-ng/blob/6be238e7039c98723edf523455a627b39788acba/arpackdef.h.in#L6 so we may need different install include directories to handle different install concurrently (https://github.com/opencollab/arpack-ng/discussions/358) https://github.com/opencollab/arpack-ng/blob/6be238e7039c98723edf523455a627b39788acba/pkg-config/arpack.pc.in#L4 and https://github.com/opencollab/arpack-ng/blob/6be238e7039c98723edf523455a627b39788acba/CMakeLists.txt#L48 So we can no more rely on stuffs like ` #include <arpack/arpack.hpp>`

Not sure here. Need to double check: https://github.com/opencollab/arpack-ng/blob/6be238e7039c98723edf523455a627b39788acba/.github/workflows/jobs.yml#L49 and https://github.com/opencollab/arpack-ng/blob/6be238e7039c98723edf523455a627b39788acba/.github/workflows/jobs.yml#L96 only runs f90 samples (that do not nedd C++ includes) as far as I remember

**Comment by FabienPean** [comment]
OK so there are two backward compatible options I could quickly experiment. All require to make one or more intermediate CMake target. 

The [first version](https://github.com/FabienPean/arpack-ng/pull/11) which provides a target `arpackng` where user calls the package as  `#include<arpack-ng/arpack.hpp>` 
  * Pros: 
    * Backward compatible with pre-existing target usage
  * Cons: 
    * Dunno yet how it can be applicable to parpack or pyarpack
    * The chosen name of the install folder must now be fixed (i.e. `arpack-ng/`)
  * Changes
    * Replace current target `arpack` by `arpackng`
    * Replace the install include directory from `${ARPACK_INSTALL_INCLUDEDIR}` to `${CMAKE_INSTALL_INCLUDEDIR}`
    * Create a new target named `arpack` as an interface library
    * Link `arpackng` to `arpack`
    * Add the install include directory `${ARPACK_INSTALL_INCLUDEDIR}`

<br>

A [second version](https://github.com/FabienPean/arpack-ng/pull/10) which provides a target `arpackng` where user can do `#include<arpack.hpp>` but requires `#include<utils/debug_c.h>`.
  * Cons: 
    * Must add an include directory in pkgconfig file
    * Create 2 intermediate targets
    * Folder name `utils/` up to debate
  * Changes
    * Replace current target `arpack` by `arpackng`
    * Install all additional headers into `${ARPACK_INSTALL_INCLUDEDIR}/utils` 
    * Create a new target named `arpack_utils` as an interface library
    * Add install include directory `${ARPACK_INSTALL_INCLUDEDIR}/utils` 
    * Create a new target named `arpack` as an interface library
    * Link `arpackng` and `arpack_utils` to `arpack`


For both must check how it interacts with parpack. It might need a similarly a new target `parpackng`

Not sure it is worth pursuing this thing, anyway it could be postponed since it is simply providing a new opt-in CMake target.

**Comment by fghoussen** [comment]
Not sure it's a good idea to do such things in a hurry!... Would be better to do thing step-by-step without breaking others (#330 #356 #358). Is this an issue if the upcoming release would not include such changes?

**Comment by FabienPean** [comment]
Yup that was my (poorly) formulated conclusion. It is already accepted as such on vcpkg so no need to be overzealous. 😃
