### ISSUE TITLE
Can you please commit configure to repo too?

### ISSUE THREAD

**Issue by markcmiller86** [opencollab/arpack-ng#40]
Without re-generating and committing configure to repo, every downloader then needs to have correct version of autoconf installed before they can use configure to build it. Having to download and installing autoconf to build another package is onerous.

**Comment by markcmiller86** [comment]
FYI...I changed AC_PREREQ(2.67) to 2.63 and LT_PREREQ(...) to 2.5.2 and only problem was AC_FC_LINE_LENGTH which I replaced with fiat setting of that flag and was able to generate a configure

**Comment by tkelman** [comment]
x-ref https://github.com/opencollab/arpack-ng/issues/29
