### ISSUE TITLE
3.4.0 Libtool wrongly set for cygwin

### ISSUE THREAD

**Issue by matzeri** [opencollab/arpack-ng#41]
On Cygwin, latest 3.4.0 arpack sets libtool wrongly. 
Comparing 3.3.0 libtool version with 3.4.0 on the build trees, I have (as extract)

-libext=a
+libext=lib

-shlibpath_overrides_runpath=yes
+shlibpath_overrides_runpath=unknown

-library_names_spec="\$libname.dll.a"
+library_names_spec="\$libname\`echo \$release | \$SED -e s/[.]/-/g\`\$versuffix\$shared_ext \$libname.lib"

-soname_spec="\`echo \$libname | sed -e s/^lib/cyg/\`\`echo \$release | \$SED -e s/[.]/-/g\`\$versuffix\$shared_ext"
+soname_spec=""

It seems libtool is incorrectly set for MSVC platform
As the changes on configure.ac are mainly base on the addition of "ax_check_compile_flag.m4" 
and its call,  I guess the root cause is there but I was unable to identify the exact culprit.

$ libtool --version
libtool (GNU libtool) 2.4.6
$ automake --version
automake (GNU automake) 1.15

**Comment by sylvestre** [comment]
Having a test patch would be appreciated, I don't have a way to test this.

**Comment by matzeri** [comment]
It will take time to have a patch. I will need to bisect the configure.ac new tests to see which one is causing the fault. May be is a corner case of Autoconf/Automake. I never had before such problem on any package that I am packing for cygwin (~ 60 use Autoconf/Automake)

**Comment by matzeri** [comment]
the problem is caused by a single line, removing it all return to normal
```
--- origsrc/arpack-ng-3.4.0/configure.ac        2016-07-02 21:52:15.000000000 +0200
+++ src/arpack-ng-3.4.0/configure.ac    2016-07-29 09:39:40.152241500 +0200
@@ -37,7 +37,6 @@ AC_ARG_VAR(SYMBOLSUFFIX, [suffix to add

 if test x"$SYMBOLSUFFIX" != x""; then
   dnl Need to rely on non-F77 features
-  AC_FC_LINE_LENGTH(unlimited)
   FFLAGS="$FFLAGS $ac_cv_fc_line_length"

   AX_CHECK_COMPILE_FLAG(-cpp, FFLAGS="$FFLAGS -cpp",
```

**Comment by sylvestre** [comment]
Good, could you write a pull request to fix that? Thanks

**Comment by matzeri** [comment]
https://github.com/opencollab/arpack-ng/pull/42

**Comment by matzeri** [comment]
There is an alternative solution. Replacing 
-AC_PROG_F77
+AC_PROG_FC
and leaving 
AC_FC_LINE_LENGTH(unlimited)

also works

**Comment by sylvestre** [comment]
patch merged
thanks!
