### ISSUE TITLE
  Make seems to be ineffective

### ISSUE THREAD

**Issue by stevedenmo** [opencollab/arpack-ng#421]
## Running/ After configuring, there is a makefile.am. in, but no makefile

[config.log](https://github.com/opencollab/arpack-ng/files/12022005/config.log)

configure: exit 2

**Comment by stevedenmo** [comment]
The problem is that I don't have a library linked to oneAPI

**Comment by fghoussen** [comment]
Log seems unavailable: I get https://cyber.dabamos.de/programming/modernfortran/random-numbers.html clicking on it.
The description of your problem is not precise enough: no way I could help. Look in CI: there is a MKL example.
I understand your problem is fixed: if so, close this issue please.
