### ISSUE TITLE
About arpackmm test suite

### ISSUE THREAD

**Issue by FabienPean** [opencollab/arpack-ng#429]
Diving further into the different pyarpack examples (due to #424), I came to check those generated for [arpackmm](https://github.com/opencollab/arpack-ng/blob/master/EXAMPLES/MATRIX_MARKET/arpackmm.sh), one can observe a few discrepancies.

In [arpackmm.sh](https://github.com/opencollab/arpack-ng/blob/master/EXAMPLES/MATRIX_MARKET/arpackmm.sh):

https://github.com/opencollab/arpack-ng/blob/e7cf106bc204ed7f7909d906fd9b1c3d18e86f76/EXAMPLES/MATRIX_MARKET/arpackmm.sh#L54-L59

1. The first regex removes non symmetric problem to be solved by the (stabilized) BiCG solver, which can handle them. (See https://eigen.tuxfamily.org/dox/group__TopicSparseSystems.html)

https://github.com/opencollab/arpack-ng/blob/e7cf106bc204ed7f7909d906fd9b1c3d18e86f76/EXAMPLES/MATRIX_MARKET/arpackmm.sh#L18-L19

2. Besides the discrepancy between decomposition solvers and iterative solvers in the first snippet, general problem are always skipped anyway, which seems an unlikely desired behavior. Especially since some of those are already solved with pyarpack (#430). 

https://github.com/opencollab/arpack-ng/blob/e7cf106bc204ed7f7909d906fd9b1c3d18e86f76/EXAMPLES/MATRIX_MARKET/arpackmm.sh#L60-L64

3. In particular the general problem always involves symmetric SPD/PD matrices so LDL and LL can work too, as used in pyarpack test suite (`pyarpack*LLT.py.in`, `pyarpack*LDLT.py.in`)

**Comment by fghoussen** [comment]
Sounds right! Any help to improve is appreciated :)

> removes non symmetric problem

At the time, I was mainly trying to cover ICB/python with non-reg tests: indeed, I had to skip some of them (as I couldn't justify spending more time on this - I was doing that at/for work!)

**Comment by fghoussen** [comment]
Letting this issue open as #433 doesn't fix everything listed here.
