### ISSUE TITLE
PkgConfig file?

### ISSUE THREAD

**Issue by dpo** [opencollab/arpack-ng#44]
I'm installing Arpack 3.4.0 using CMake on OSX but I'm missing the pkgconfig file `arpack.pc`. It's installed when I used `configure`, but not `cmake`. Any ideas?

Thanks.

**Comment by sylvestre** [comment]
The cmake build is not managing it. This should be easy to fix.

**Comment by dpo** [comment]
Thanks. Is there an ETA on this?

**Comment by sylvestre** [comment]
You should try to propose a PR for this.
