### ISSUE TITLE
p*napps cause deadlock when using custom communicators

### ISSUE THREAD

**Issue by iskakoff** [opencollab/arpack-ng#46]
If the arnoldi runs on a custom communicator created for some subset of available cpus and after successful completion the second execution of the arnoldi with a communicator for a larger number subset of available cpus it will cause deadlock due to the following condition in code:

`data       first / .true. /`
`c`
`c     %-----------------------%`
`c     | Executable Statements |`
`c     %-----------------------%`
`c`
`      if (first) then`
`... `
`     first = .false.`
`...`
`endif`

the variable `first` is set to `false` in the first subset of cpus and will avoid a condition body evaluation, but other cpus have `first` equals to `true` and will evaluate condition body. Inside the condition body there is a `p*lamch10` call where the `MPI_ALLREDUCE` is called.

the possible workaround is to perform `MPI_ALLREDUCE(...MPI_LAND...)` for the variable `first` to be sure that all cpus inside communicator have the same value. But maybe there is a better solution.

**Comment by sylvestre** [comment]
It would be nice if you could try a fix (or at least a test to help other volunteers to reproduce it).

**Comment by sylvestre** [comment]
Many thanks!
