### ISSUE TITLE
Compilation fails with ifort -warn all

### ISSUE THREAD

**Issue by opoplawski** [opencollab/arpack-ng#49]
When compiling with the Intel Fortran compiler and -warn all I get many errors like the following:
```
ifort  -O3 -g -warn all -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -grecord-gcc-switches -m64 -axSSE3,SSSE3,SSE4.1,SSE4.2,CORE-AVX2,COMMON-AVX512 -c -o zndrv2.o zndrv2.f
zndrv2.f(343): error #6633: The type of the actual argument differs from the type of the dummy argument.   [V]
               call av(n, v(1,j), ax)
--------------------------^
zndrv2.f(343): error #6633: The type of the actual argument differs from the type of the dummy argument.   [AX]
               call av(n, v(1,j), ax)
----------------------------------^
```

**Comment by sylvestre** [comment]
Well, if you want to volunteer to fix these warnings, this is more than welcome

**Comment by opoplawski** [comment]
Turns out that this is triggered by using 'make -j N'.  ifort with -warn interfaces (which is include in all) will generate temporary source files to do the argument checking.  With multiple simultaneous compiles of different source files with the same routine defined differently it triggered this error.
