### ISSUE TITLE
Problem with Complex Generalized Eigenvalue problem (Double precision ok)

### ISSUE THREAD

**Issue by jfrench7** [opencollab/arpack-ng#57]
When I use the single & double precision complex ARPACK routines using the generalized approach, for the non-shift-invert version the problem does not converge, and for the shift-invert problem the eigenvalues become all zero.

To investigate further, I tried a simpler problem with real eigenvalues & eigenvectors.

Double precision ARPACK:  works for all forms of generalized (& not generalized)

Single & double complex ARPACK:
    Generalized No shift-invert:  does not converge
    Generalized With shift-invert:  converges to zero eigenvalues (well, eigenvalues = shift)
    Not Generalized:  works (convert "Ax = LMx" to  "M^-1 A x  = L I x" & solve as not generalized)

I have attached sample A and M matrices to this message.  The problem is designed so that the eigenvalues should be 0, 1, 4, 9, 16, 25, 36, etc.  A is the Laplacian, so technically Ax = 0 (0 eigenvalue) is a solution, which makes A technically singular, but I don't think it is a problem as it still works in double precision.

Please let me know if there's anything else that I could supply in order to help fix this problem.

It doesn't appear to allow me to attach the files - instructions on how to do that would help.

**Comment by jfrench7** [comment]
Apparently Firefox doesn't work with github well.  Here are A & M from "Ax = L Mx":
[A.txt](https://github.com/opencollab/arpack-ng/files/819992/A.txt)
[B.txt](https://github.com/opencollab/arpack-ng/files/819991/B.txt)

These are 303x303 matrices.  Let me know if row or column packed would help (they are very sparse).

**Comment by sylvestre** [comment]
> Apparently Firefox doesn't work with github well. 
Can you tell me more?

Would need the code using these matrices too.

**Comment by jfrench7** [comment]
I tried to download the latest version to make sure the problem hadn't been already addressed, and the zip file does not contain the configure program and many Makefile.in files.  Is someone working on that?

**Comment by jfrench7** [comment]
Nevermind - I discovered my "B" was not hermitian semi-positive definite.  Works fine now.  Closing issue.
