### ISSUE TITLE
cmake build can't generate static libraries

### ISSUE THREAD

**Issue by rathann** [opencollab/arpack-ng#62]
When building arpack-ng 3.5.0 using cmake, I don't see any option to build static libraries. Would it be possible to add it?

**Comment by fghoussen** [comment]
I add a (very...) quick look at that. Should be OK with incoming PR at my side.

**Comment by davydden** [comment]
@rathann 

```
-DBUILD_SHARED_LIBS=OFF
``` 
should do the trick.

**Comment by rathann** [comment]
Not really, I want to build both shared and static.

**Comment by davydden** [comment]
>  I want to build both shared and static.

you would need to run out-of-source configure twice, AFAIK `cmake` does not have any mechanisms to easily build both.

**Comment by fghoussen** [comment]
>Not really, I want to build both shared and static.

Yes, @davydden is right: you need to run twice.
Neither autotools nor cmake allow to install static and shared at the same time.

**Comment by rathann** [comment]
@fghoussen That's not true regarding autotools. The current Fedora package builds both shared and static libraries in one build: https://src.fedoraproject.org/rpms/arpack/blob/master/f/arpack.spec#_104 .

**Comment by fghoussen** [comment]
@rathann you seem to be right for autotools (didn't know that). for cmake, seems you need to run twice.

**Comment by sylvestre** [comment]
Yeah, and I don't think it is a big deal :)
