### ISSUE TITLE
cmake build offers no option to run EXAMPLES tests

### ISSUE THREAD

**Issue by rathann** [opencollab/arpack-ng#64]
When arpack-ng 3.5.0 is configured using cmake, the tests in EXAMPLES are not run, whereas when using autotools, they are (72 more tests are run this way). Please update the CMakeFiles.txt to include running EXAMPLES tests, like configure'd Makefile does.

**Comment by sylvestre** [comment]
@fghoussen As you are touching that, could you have a look?

**Comment by fghoussen** [comment]
I already noticed that cmake provided check but no test (don't know neither why nor what the difference is supposed to be). check is OK (I modified that recently). I added a test target (see dedicated PR).

**Comment by fghoussen** [comment]
BTW, this should be OK now ? If yes, I guess you can close this

**Comment by sylvestre** [comment]
Sure
