### ISSUE TITLE
Building the Visual Studio project fails

### ISSUE THREAD

**Issue by elezar** [opencollab/arpack-ng#8]
When building the Visual Studio project, the build fails complaining about undefined symbols. These are:
```
_slahqr2_
_dlahqr2_
```

This seems to be as simple as adding them to the list of source files. I have forked the repo, and will see if I can submit a pull request.

**Comment by sylvestre** [comment]
Are you planning to submit a PR ?

**Comment by elezar** [comment]
I thought I did. It seems as if my changes are already in the repo and I see that the changes have already been merged in commit 5cd31c69d40a163044a64077590d50b2ce312d87.

Thus closing the issue.

**Comment by sylvestre** [comment]
Oh, my bad.
It was this PR Tired https://github.com/opencollab/arpack-ng/pull/9
