### ISSUE TITLE
CMake minimum version not tested

### ISSUE THREAD

**Issue by dbeurle** [opencollab/arpack-ng#88]
I noticed the Travis build script doesn't test against the specified minimum 2.8.6 but 3.1.9 instead.  Which one is the intended version?

**Comment by dbeurle** [comment]
@sylvestre Are you ok to bump the CMake version from 2.x to 3.1?  I can tidy up the CMAKE_CXX_FLAGS with this.

**Comment by sylvestre** [comment]
Hmm, Ubuntu LTS don't have 3.1 :(
https://launchpad.net/ubuntu/+source/cmake
So, not sure we want to upgrade this dependency _just_ for that

**Comment by dbeurle** [comment]
Roger that.
